spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wellkept_db?useSSL=false
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    jpa:
      repositories:
        enabled: true